### ISSUE TITLE
How to handle different positions

### ISSUE THREAD

**Issue by Nasicus** [scttcper/ngx-toastr#322]
Hi!

Great project! I just wanted to know if you have any recommendations on how to handle different positioning of the toaster.

For example in my app I'd like to have to toaster on top right for default (`toast-top-right`), but on smaller screens - or let's say mobile - I'd like to have it on bottom (`toast-bottom-center`).

What is the best approach here?
Use a custom container for the toast and then write own css media rules to display the toast on different positions on the screen?
What I don't like about that is, that I then cannot use the predefined positioning classes. 
Or is it a better idea to listen for the window size and size changes via javascript, and depending on the size applying a different "standard"-toastr position class on the container?
Or is there even an easier way?

Thanks for your replies in advance :)

**Comment by scttcper** [comment]
If I had to implement this I'd probably make a service that listens to screen size and imports ToastrService. From there i'd do whatever I needed for screen size and change `toastrService. toastrConfig` directly. Which would change the global defaults for all future toasts.

**Comment by scttcper** [comment]
Or i'd do it using css. Which is probably the better option

**Comment by scttcper** [comment]
```css
.toast-top-right {
	keep as normal 
}

@media (css query) {
	copy settings from bottom center and overwrite top right
}
```

**Comment by yarrgh** [comment]
I'd go with the css option. Much cleaner and it's simple.

This worked for me:
```css
.toast-top-right {
  top: 12px;
  right: 12px;
}

@media (max-width: 575.98px) {
  .toast-top-right {
    top: unset;
    bottom: 0;
    right: 0;
    width: 100%;
  }
  .toast-container.toast-top-right .toast {
    width: 300px;
    margin-left: auto;
    margin-right: auto;
  }
}
```
