### ISSUE TITLE
Close button styling issue with Bootstrap 4

### ISSUE THREAD

**Issue by velvok** [scttcper/ngx-toastr#427]
Close button is not styled correctly when used with Bootstrap 4.

![image](https://user-images.githubusercontent.com/11169743/39490849-36ac3d6e-4d58-11e8-9466-991c6b098bae.png)

**Comment by scttcper** [comment]
I just read your comment in that issue as well. I’m not able to reproduce this. Is there a specific browser?

I assume you’re loading bootstrap and then the bs4 template

**Comment by yarrgh** [comment]
Just opened a pull request to fix this. You can fix this in the mean time by adding this to your styles.css:

```css
.toast-close-button {
  background: transparent;
  border: 0;
  padding: 0;
}
```
