### ISSUE TITLE
toast.success() toast have 2 checkmarks

### ISSUE THREAD

**Issue by hengchenvoon** [scttcper/ngx-toastr#73]
According to CSS:

```CSS
#toast-container .toast.toast-success {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR…0CWuABKgnRki9lLseS7g2AlqwHWQSKH4oKLrILpRGhEQCw2LiRUIa4lwAAAABJRU5ErkJggg==) !important;
}

#toast-container > .toast-success:before {
    content: "\F00C";
}
```

These 2 CSS generate checkmark of their own, which end up showing 2 checkmarks instead of 1 on `success()`, is there any reason for this?
